version: '3.8'

services:
  #  app:
  #    build: .
  #    ports:
  #      - "${SERVER_PORT}:${SERVER_PORT}"
  #    depends_on:
  #      - db
  #    environment:
  #      SERVER_PORT: ${SERVER_PORT}
  #      DB_URL: ${DB_URL}
  #      DB_USERNAME: ${DB_USERNAME}
  #      DB_PASSWORD: ${DB_PASSWORD}
  #      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
  #      MAIL_HOST: ${MAIL_HOST}
  #      MAIL_PORT: ${MAIL_PORT}
  #      MAIL_USERNAME: ${MAIL_USERNAME}
  #      MAIL_PASSWORD: ${MAIL_PASSWORD}
  #      TOKEN_SIGNING_KEY: ${TOKEN_SIGNING_KEY}
  #      TOKEN_LIFETIME: ${TOKEN_LIFETIME}

  db:
    image: postgres:15
    container_name: hack-hero-database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
  #    volumes:
  #      - ./pgdata:/var/lib/postgresql/data


networks:
  hackhero-network:
    driver: bridge

volumes:
  pgdata:
