version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hackhero-database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hackhero-network

networks:
  hackhero-network:
    driver: bridge

volumes:
  pgdata:
