server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth-module:8081
          predicates:
            - Path=/auth/**
        - id: core
          uri: http://core-module:8082
          predicates:
            - Path=/api/v1/**
