server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: core
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/**

auth:
  module:
    url: http://localhost:8081
