server:
  port: 8081
spring:
  application:
    name: auth-module
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

clients:
  core-module: ${CORE_MODULE_URL}

token:
  signingKey: ${TOKEN_SIGNING_KEY}
  lifetime: ${TOKEN_LIFETIME}